### ISSUE TITLE
UI Review

### ISSUE THREAD

**Issue by amitferman** [Husky-Navigation-Services/Husky-Navigation#1]
The initial UI design is finished:
![image](https://user-images.githubusercontent.com/23445218/100286154-1fe0fa80-2f27-11eb-9b8b-a06714f34fdb.png)
If you click the husky icon, you get:
![image](https://user-images.githubusercontent.com/23445218/100286190-371fe800-2f27-11eb-8fc8-dbead2ea14dc.png)
with a nice transition. Any recommendations for changes?

**Comment by amitferman** [comment]
New Progress on UI!
![image](https://user-images.githubusercontent.com/23445218/100306031-41f27100-2f57-11eb-8537-0d5ca39b812a.png)

**Comment by dberezansky** [comment]
I think that the initial UI was a lot better in terms of readability. Sometimes I think keeping it simple is something the user appreciates and the font is important because subconsciously it is what the user is interacting with most. Reading simply out of force of instinct. The logo is beautify placed on the other hand. As you mentioned in the chat having some sort of extra features integrated would be good @amitferman All in all I think the initial design was perhaps the best. It might be worth making the end location marker a different color then the original for the sake of differentiating. I think one think we might consider would be linking an about us section of some type or giving the logo more purpose. For instance, pressing our logo twice would bring the user to a distinct place. If we harness that we could even add "Easter eggs" just like Discord does such as pressing the logo 10 times in succession brings you to Sylvan grove in the map (this is just me throwing out ideas, by no means do we have to implement this. So far overall the UI is great and in good shape. I am not sure how the animations @amitferman you were talking about worked out so feel free to message me the details later. Otherwise, this is good solid initial work!
